improve run

diff --git a/c/run b/c/run
--- a/c/run
+++ b/c/run
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ ! -f "$1.c" ]; then
+    echo "File not found: $1.c"
+    exit 1
+fi
+
 gcc $1.c -o $1
 cat input | ./$1
 rm $1
